# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: ruby-lang.org
    authentication: :nil
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: ruby-lang.org
    authentication: :nil
