# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    host: 'redmine.ruby-lang.org'
    domain: ruby-lang.org
    authentication: :nil
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: 127.0.0.1
    port: 25
    domain: local.yugui.jp
    host: local.yugui.jp
    authentication: ~
